name: Build APK Android
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build APK
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Aplikasi-Radio-Siap-Pakai
        path: app/build/outputs/apk/debug/app-debug.apk
